# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.vista.funciones import *
from src.modelo.conexion.conexionJava import *

class Ui_MainWindow3(object):
    def __init__(self, coord=None):
        self.coordinador = coord

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.imagen = QtWidgets.QLabel(self.centralwidget)
        self.imagen.setGeometry(QtCore.QRect(0, 0, 1240, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagen.sizePolicy().hasHeightForWidth())
        self.imagen.setSizePolicy(sizePolicy)
        self.imagen.setText("")
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")

        self.hola = BorderedTextLabel(self.centralwidget)
        self.hola.setGeometry(QtCore.QRect(10, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.hola.setFont(font)
        self.hola.setObjectName("hola")

        self.hola_2 = BorderedTextLabel(self.centralwidget)
        self.hola_2.setGeometry(QtCore.QRect(220, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.hola_2.setFont(font)
        self.hola_2.setText("")
        self.hola_2.setAlignment(Qt.AlignLeft) 
        self.hola_2.setObjectName("hola_2")

        self.c = concesionario(self.centralwidget)

        self.copiaSeguridad = QtWidgets.QPushButton(self.centralwidget)
        self.copiaSeguridad.setGeometry(QtCore.QRect(1180, 50, 50, 50))
        self.copiaSeguridad.setObjectName("Copia de seguridad")
        self.copiaSeguridad.setToolTip("Copia de seguridad")
        self.copiaSeguridad.setText("Copia")


        self.Trabajador = QtWidgets.QPushButton(self.centralwidget)
        self.Trabajador.setGeometry(QtCore.QRect(400, 650, 151, 41))
        self.Trabajador.setObjectName("Trabajador")
        self.Trabajador.setToolTip("Añade, elimina, modifica o busca trabajadores")

        self.Taller = QtWidgets.QPushButton(self.centralwidget)
        self.Taller.setGeometry(QtCore.QRect(580, 650, 151, 41))
        self.Taller.setObjectName("Taller")
        self.Taller.setToolTip("Añade, elimina modifica o busca maquinaria en un taller")

        self.Cliente = QtWidgets.QPushButton(self.centralwidget)
        self.Cliente.setGeometry(QtCore.QRect(210, 650, 151, 41))
        self.Cliente.setObjectName("Cliente")
        self.Cliente.setToolTip("Añade, elimina, modifica o busca clientes")

        self.Concesionario = QtWidgets.QPushButton(self.centralwidget)
        self.Concesionario.setGeometry(QtCore.QRect(20, 650, 151, 41))
        self.Concesionario.setObjectName("Concesionario")
        self.Concesionario.setToolTip("Añade, elimina, modifica o busca concesionarios")

        self.Almacen = QtWidgets.QPushButton(self.centralwidget)
        self.Almacen.setGeometry(QtCore.QRect(760, 650, 151, 41))
        self.Almacen.setObjectName("Almacen")
        self.Almacen.setToolTip("Añade, elimina, modifica o busca piezas en un almacen")

        self.vehiculos = QtWidgets.QPushButton(self.centralwidget)
        self.vehiculos.setGeometry(QtCore.QRect(940, 650, 151, 41))
        self.vehiculos.setObjectName("Vehiculos")
        self.vehiculos.setToolTip("Añade, elimina, modifica o busca vehiculos")

        self.ventas = QtWidgets.QPushButton(self.centralwidget)
        self.ventas.setGeometry(QtCore.QRect(20, 580, 151, 41))
        self.ventas.setObjectName("Ventas")
        self.ventas.setToolTip("Añade, elimina, modifica o busca ventas")

        self.pago = QtWidgets.QPushButton(self.centralwidget)
        self.pago.setGeometry(QtCore.QRect(940, 580, 151, 41))
        self.pago.setObjectName("Pagos")
        self.pago.setToolTip("Añade, elimina, modifica o busca pagos")


        #self.notificaciones = 
        #self.combo_box = QtWidgets.QComboBox(self.centralwidget)
        #self.combo_box.setGeometry(1040, 10, 180, 30)
        #self.combo_box.setStyleSheet("background-color: transparent; border: 2px solid white; color: white; border-radius: 10px;")

        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 50, 141, 61))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        
        #cargo el boton atras
        self.atras = setAtras(self.centralwidget)
        
        
        self.lista = [self.Concesionario, self.Cliente, self.Trabajador, self.Taller, self.Almacen, self.vehiculos, self.ventas, self.pago, self.copiaSeguridad]
        
        
        self.checkBox.stateChanged.connect(lambda: modoClOs(self.checkBox, self.imagen, self.lista))
        modoClOs(self.checkBox, self.imagen, self.lista)
        
        self.copiaSeguridad.clicked.connect(lambda: self.copia())
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    

    def copia(self):
        root = tk.Tk()
        root.title("Copia de Seguridad")
        root.geometry("400x200")

        boton_copia = tk.Button(root, text="Realizar Copia de Seguridad", command=realizar_copia_seguridad)
        boton_copia.pack(pady=20)

        root.mainloop()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ventana del administrador"))
        self.hola.setText(_translate("MainWindow", "Hola de nuevo"))
        self.Trabajador.setText(_translate("MainWindow", "Trabajadores"))
        self.Taller.setText(_translate("MainWindow", "Talleres"))
        self.Cliente.setText(_translate("MainWindow", "Clientes"))
        self.Concesionario.setText(_translate("MainWindow", "Concesionarios"))
        self.Almacen.setText(_translate("MainWindow", "Almacenes"))
        self.vehiculos.setText(_translate("MainWindow", "Vehiculos"))
        self.ventas.setText(_translate("MainWindow", "Ventas"))
        self.pago.setText(_translate("MainWindow", "Pago"))
        self.checkBox.setText(_translate("MainWindow", "Modo oscuro"))


    def setCoordinador(self, coord) -> None:
        self.coordinador = coord
    
#import botonAtrasBlanco
#import botonAtrasBlancoAzul
#import botonAtras
#import nissan2
#import nissanGtrClaro

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
"""