# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaIniciarSesion.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.modelo.vo.ClienteVO import Cliente
from src.modelo.vo.PlantillaTrabajadorVO import PlantillaTrabajadorVO


class Ui_MainWindow2(object):
    def __init(self, coord=None):
        self.coordinador = coord


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 720)
        MainWindow.setMaximumSize(QtCore.QSize(3862, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1240, 720))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-image: url(:/direccion2/imageDesenfocada.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/direccion2/imageDesenfocada.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(470, 160, 300, 400))
        self.frame.setStyleSheet("background-color: #282e2a;\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.DNI = QtWidgets.QLabel(self.frame)
        self.DNI.setGeometry(QtCore.QRect(45, 30, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DNI.setFont(font)
        self.DNI.setObjectName("DNI")
        self.LineaDni = QtWidgets.QLineEdit(self.frame)
        self.LineaDni.setGeometry(QtCore.QRect(40, 100, 220, 31))
        self.LineaDni.setStyleSheet("background-color:white;\n"
"\n"
"border: 2px solid gray;\n"
"border-radius: 10px; /* Ajusta el radio según tus preferencias */\n"
"padding: 5px; /* Opcional: ajusta el espaciado interior */\n"
"\n"
"")
        self.LineaDni.setText("")
        self.LineaDni.setObjectName("LineaDni")
        self.Contra = QtWidgets.QLabel(self.frame)
        self.Contra.setGeometry(QtCore.QRect(45, 170, 220, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Contra.setFont(font)
        self.Contra.setObjectName("Contra")
        self.LineaContra = QtWidgets.QLineEdit(self.frame)
        self.LineaContra.setGeometry(QtCore.QRect(40, 240, 220, 31))
        self.LineaContra.setStyleSheet("background-color:white;\n"
"\n"
"border: 2px solid gray;\n"
"border-radius: 10px; /* Ajusta el radio según tus preferencias */\n"
"padding: 5px; /* Opcional: ajusta el espaciado interior */\n"
"\n"
"")
        self.LineaContra.setText("")
        self.LineaContra.setObjectName("LineaContra")
        self.IniciarSesion = QtWidgets.QPushButton(self.frame)
        self.IniciarSesion.setGeometry(QtCore.QRect(100, 350, 100, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.IniciarSesion.setFont(font)
        self.IniciarSesion.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
    "QPushButton:pressed {"
    "background-color: #2980b9;"
"}"
)
        self.IniciarSesion.setObjectName("IniciarSesion")
        self.Incorrecto = QtWidgets.QLabel(self.frame)
        self.Incorrecto.setEnabled(True)
        self.Incorrecto.setGeometry(QtCore.QRect(10, 300, 281, 21))
        self.Incorrecto.setObjectName("Incorrecto")
        self.Incorrecto.setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DNI.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">DNI:</span></p></body></html>"))
        self.Contra.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Contraseña:</span></p></body></html>"))
        self.IniciarSesion.setText(_translate("MainWindow", "Iniciar sesion"))
        self.Incorrecto.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ff0000;\">Dni o contraseña incorrectos. Vuelve a intentarlo</span></p></body></html>"))

    def hacerVisible(self, arg):
        self.Incorrecto.setVisible(arg)
    
    def setCoordinador(self, coord):
        self.coordinador = coord

    def obtener_datos_ingresados(self):
        # Obtener el texto ingresado en los lineedits de DNI y contraseña
        trabajador = PlantillaTrabajadorVO(
            IDtrabajador= self.LineaDni.text(),
            Contraseña= self.LineaContra.text()
        )


        cliente = Cliente(
                IDcliente =  self.LineaDni.text(),
                Contrasenia = self.LineaContra.text()
            )
        
        a = self.coordinador.comprobarIniciarSesion(cliente) 
        b = self.coordinador.comprobarIniciarSesion(trabajador)

        if a[0] == "cliente":
            return a
        elif b[0] == "trabajador":
            return b
        else:
            print("Error en el DNI o la contrasenia")
            return False
        



import imagenDes_rc

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
"""