# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init(self, coordinador=None):
        self.coordinador = coordinador

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(3840, 2160))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget.setMaximumSize(QtCore.QSize(3840, 2160))
        self.centralwidget.setObjectName("centralwidget")
        self.Bienvenido = QtWidgets.QLabel(self.centralwidget)
        self.Bienvenido.setGeometry(QtCore.QRect(528, 50, 185, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bienvenido.sizePolicy().hasHeightForWidth())
        self.Bienvenido.setSizePolicy(sizePolicy)
        self.Bienvenido.setMinimumSize(QtCore.QSize(170, 17))
        self.Bienvenido.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Bienvenido.setFont(font)
        self.Bienvenido.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Bienvenido.setTextFormat(QtCore.Qt.AutoText)
        self.Bienvenido.setAlignment(QtCore.Qt.AlignCenter)
        self.Bienvenido.setWordWrap(False)
        self.Bienvenido.setObjectName("Bienvenido")
        self.Continuar = QtWidgets.QPushButton(self.centralwidget)
        self.Continuar.setGeometry(QtCore.QRect(515, 610, 211, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Continuar.sizePolicy().hasHeightForWidth())
        self.Continuar.setSizePolicy(sizePolicy)
        self.Continuar.setMinimumSize(QtCore.QSize(84, 14))
        self.Continuar.setMaximumSize(QtCore.QSize(500, 82))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Continuar.setFont(font)
        self.Continuar.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
    "QPushButton:pressed {"
    "background-color: #2980b9;"
"}"
)
        self.Continuar.setObjectName("Continuar")
        self.Foto = QtWidgets.QLabel(self.centralwidget)
        self.Foto.setEnabled(True)
        self.Foto.setGeometry(QtCore.QRect(0, 0, 1240, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Foto.sizePolicy().hasHeightForWidth())
        self.Foto.setSizePolicy(sizePolicy)
        self.Foto.setMinimumSize(QtCore.QSize(640, 480))
        self.Foto.setMaximumSize(QtCore.QSize(3840, 2160))
        self.Foto.setStyleSheet("background-image: url(:/direccion/black-porsche-2020-pp.jpg);")
        self.Foto.setText("")
        self.Foto.setPixmap(QtGui.QPixmap(":/direccion/black-porsche-2020-pp.jpg"))
        self.Foto.setScaledContents(True)
        self.Foto.setObjectName("Foto")
        self.Foto.raise_()
        self.Bienvenido.raise_()
        self.Continuar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Bienvenido.setText(_translate("MainWindow", "Bienvenido"))
        self.Continuar.setText(_translate("MainWindow", "Continuar"))


    def setCoordinador(self, coord) -> None:
        self.coordinador = coord

import imagen_rc

"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
"""