# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def __init(self, coord=None):
        self.coordinador = coord

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1240, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1240, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1200))
        self.centralwidget.setObjectName("centralwidget")
        self.imagen = QtWidgets.QLabel(self.centralwidget)
        self.imagen.setGeometry(QtCore.QRect(0, 0, 1240, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagen.sizePolicy().hasHeightForWidth())
        #print(self.image)
        self.imagen.setSizePolicy(sizePolicy)
        self.imagen.setMinimumSize(QtCore.QSize(1240, 720))
        self.imagen.setMaximumSize(QtCore.QSize(1920, 1200))
        self.imagen.setStyleSheet("background-image: url(:/direccion/nissan_skyline_gt_r_r34-HD.jpg);")
        self.imagen.setText("")
        #self.imagen.setScaledContents(True)
        self.imagen.setPixmap(QtGui.QPixmap("nissan_skyline_gt_r_r34-HD.jpg"))
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")

        print(self.imagen.size())
        #pixmap = QtGui.QPixmap("nissan_skyline_gt_r_r34-HD.jpg")
        #scaled_pixmap = pixmap.scaled(self.imagen.size(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation)
        #self.imagen.setPixmap(scaled_pixmap)


        self.hola = QtWidgets.QLabel(self.centralwidget)
        self.hola.setGeometry(QtCore.QRect(10, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.hola.setFont(font)
        self.hola.setStyleSheet("color: white")
        self.hola.setObjectName("hola")
        self.hola_2 = QtWidgets.QLabel(self.centralwidget)
        self.hola_2.setGeometry(QtCore.QRect(230, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.hola_2.setFont(font)
        self.hola_2.setStyleSheet("color: white")
        self.hola_2.setText("")
        self.hola_2.setObjectName("hola_2")
        self.aniadirTr = QtWidgets.QPushButton(self.centralwidget)
        self.aniadirTr.setGeometry(QtCore.QRect(20, 650, 151, 41))
        self.aniadirTr.setObjectName("aniadirTr")
        self.eliminarTr = QtWidgets.QPushButton(self.centralwidget)
        self.eliminarTr.setGeometry(QtCore.QRect(210, 650, 151, 41))
        self.eliminarTr.setObjectName("eliminarTr")
        self.aniadirCl = QtWidgets.QPushButton(self.centralwidget)
        self.aniadirCl.setGeometry(QtCore.QRect(400, 650, 151, 41))
        self.aniadirCl.setObjectName("aniadirCl")
        self.eleminarCl = QtWidgets.QPushButton(self.centralwidget)
        self.eleminarCl.setGeometry(QtCore.QRect(580, 650, 151, 41))
        self.eleminarCl.setObjectName("eleminarCl")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hola.setText(_translate("MainWindow", "Hola de nuevo"))
        self.aniadirTr.setText(_translate("MainWindow", "Añadir trabajador"))
        self.eliminarTr.setText(_translate("MainWindow", "Eliminar trabajador"))
        self.aniadirCl.setText(_translate("MainWindow", "Añadir cliente"))
        self.eleminarCl.setText(_translate("MainWindow", "Eliminar cliente"))

    
    def setCoordinador(self, coord):
        self.coordinador = coord

import nissanGtr



"""
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
"""